postprocess:
	rm -f ..\index.html
	rm -rf ..\static
	rm -rf ..\favicon.ico
	rm -rf ..\contact
	cp .\build\index.html ../
	mkdir ..\contact
	cp .\build\index.html ..\contact
	cp .\build\favicon.ico ..\
	cp -r .\build\static ..\